query PostBySlug($slug: String!)  {
    posts(where:{slug: $slug}) {
        id,
        slug,
        image {
            url
        },
        published_at,
        name,
        content,
        tags {
          name
        }
    }
}