query Posts($tags: [String]) {
    posts(where: {tags: { name: $tags}}) {
        id,
        slug,
        image {
            url
        },
        published_at,
        name,        
        content,
        description
        tags {
          name
        }
    }
}